version: '3.8'

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://report:8000
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend

  report:
    build:
      context: ./report
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: olap_db
      DB_USER: report
      DB_PASSWORD: 'p@ssw0rd'
      JWKS_URL: 'http://keycloak:8080/realms/reports-realm/protocol/openid-connect/certs'
    depends_on:
      - olap_db

  olap_db:
      image: clickhouse/clickhouse-server:latest
      ports:
        - "8123:8123"
        - "9431:9000"
      volumes:
        - olap_db_data:/var/lib/clickhouse
        - ./olap-db:/docker-entrypoint-initdb.d
        - ./olap-db:/var/lib/clickhouse/user_files
        - ./olap-db/users.xml:/etc/clickhouse-server/users.d/users.xml
      healthcheck:
        test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1'"]
        interval: 1s
        timeout: 3s
        retries: 30

volumes:
  keycloak_db_data:
  olap_db_data: